baseURL = "https://nozyzy.github.io/"
theme = "LoveIt"
title = "NozZy"
publishDir = "docs"
enableEmoji = true

languageCode = "en-us"
languageName = "English"
hasCJKLanguage = false

[author]
  name = "NozZy"
  email = "nozzy@club-rezo.net"
  link = "nozyzy.github.io"
  sex = "M"

# default amount of posts in each pages
paginate = 10


# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Writeups"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = "Writeups"
  [[menu.main]]
    weight = 2
    identifier = "articles"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Articles"
    url = "/articles/"
    # title will be shown when you hover on this menu link
    title = "Articles"
  [[menu.main]]
    weight = 3
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = ""
  [[menu.main]]
    weight = 4
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = ""
  [[menu.main]]
    weight = 5
    identifier = "aboutme"
    pre = ""
    post = ""
    name = "./aboutme"
    url = "/aboutme"
    title = ""


# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[params]
  defaultTheme = "auto"
  gitRepo = ""
  fingerprint = "sha256"
  dateFormat = "02-01-2006"
  title = "NozZy"
  description = "French Cybersecurity student and CTF enjoyer."
  images = ["assets/nozzy.png"]


# Header config
[params.header]
  desktopMode = "fixed"
  mobileMode = "auto"

[params.header.title]
  logo = "https://avatars.githubusercontent.com/u/60878689?v=4"
  name = "NozZy"
  typeit = false

# Footer config
[params.footer]
  enable = true
  custom = ''
  hugo = true
  copyright = true
  author = true
  since = 2023
  # license info (HTML format is supported)
  license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'

[params.section]
  # special amount of posts in each section page
  paginate = 20
  # date format (month and day)
  dateFormat = "01-02"
  # amount of RSS pages
  rss = 10

[params.list]
  # special amount of posts in each list page
  paginate = 20
  # date format (month and day)
  dateFormat = "01-02"
  # amount of RSS pages
  rss = 10

[params.app]
  # optional site title override for the app when added to an iOS home screen or Android launcher
  title = "NozZy"
  # whether to omit favicon resource links
  noFavicon = false
  # modern SVG favicon to use in place of older style .png and .ico files
  svgFavicon = ""
  # Android browser theme color
  themeColor = "#ffffff"
  # Safari mask icon color
  iconColor = "#5bbad5"
  # Windows v8-10 tile color
  tileColor = "#da532c"

# LoveIt NEW | 0.2.0 Search config
[params.search]
  enable = true
  type = "lunr"
  contentLength = 4000
  placeholder = ""
  maxResultLength = 10
  snippetLength = 30
  highlightTag = "em"
  absoluteURL = false
  [params.search.algolia]
    index = ""
    appID = ""
    searchKey = ""

# Home page config
[params.home]
  rss = 10
  [params.home.profile]
    enable = true
    gravatarEmail = ""
    avatarURL = "/images/nozzy.png"
    title = "NozZy"
    subtitle = "French Cybersecurity student and CTF enjoyer."
    typeit = true
    social = true

  # Home page posts
  [params.home.posts]
    enable = true
    paginate = 6
    defaultHiddenFromHomePage = false

# Social config about the author
[params.social]
  GitHub = "NozyZy"
  Linkedin = ""
  Twitter = "Nozzouille"
  Discord = "nozyzy"
  RootMe= "NozZy"
  HackTheBox = "NozyZy"
  Email = "nozzy@club-rezo.net"
  #RSS = true

[params.page]
  hiddenFromHomePage = false
  hiddenFromSearch = false
  twemoji = false
  lightgallery = false
  ruby = true
  fraction = true
  fontawesome = true
  linkToMarkdown = true
  rssFullText = false

[params.page.toc]
  enable = true
  keepStatic = false
  auto = true

[params.page.math]
  enable = true
  inlineLeftDelimiter = ""
  inlineRightDelimiter = ""
  blockLeftDelimiter = ""
  blockRightDelimiter = ""
  copyTex = true
  mhchem = true

[params.page.code]
  copy = true
  maxShownLines = 30

[params.page.mapbox]
  accessToken = ""
  lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
  darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
  navigation = true
  geolocate = true
  scale = true
  fullscreen = true

[params.page.share]
  enable = true
  Twitter = true
  Facebook = false
  Linkedin = true
  Whatsapp = false
  Pinterest = false
  Tumblr = false
  HackerNews = true
  Reddit = false
  VK = false
  Buffer = false
  Xing = false
  Line = true
  Instapaper = false
  Pocket = false
  Flipboard = false
  Weibo = true
  Blogger = false
  Baidu = false
  Odnoklassniki = false
  Evernote = false
  Skype = false
  Trello = false
  Mix = false

[params.page.comment]
  enable = false

[params.page.comment.disqus]
  enable = false
  shortname = ""

[params.page.comment.gitalk]
  enable = false
  owner = ""
  repo = ""
  clientId = ""
  clientSecret = ""

[params.page.comment.valine]
  enable = false
  appId = ""
  appKey = ""
  placeholder = ""
  avatar = "mp"
  meta= ""
  pageSize = 10
  # automatically adapt the current theme i18n configuration when empty
  lang = ""
  visitor = true
  recordIP = true
  highlight = true
  enableQQ = false
  serverURLs = ""
  # LoveIt NEW | 0.2.6 emoji data file name, default is "google.yml"
  # ["apple.yml", "google.yml", "facebook.yml", "twitter.yml"]
  # located in "themes/LoveIt/assets/lib/valine/emoji/" directory
  # you can store your own data files in the same path under your project:
  # "assets/lib/valine/emoji/"
  emoji = ""

[params.page.comment.facebook]
  enable = false
  width = "100%"
  numPosts = 10
  appId = ""
  languageCode = ""

[params.page.comment.telegram]
  enable = false
  siteID = ""
  limit = 5
  height = ""
  color = ""
  colorful = true
  dislikes = false
  outlined = false

[params.page.comment.commento]
  enable = false

[params.page.comment.utterances]
  enable = false
  # owner/repo
  repo = "https://github.com/NozyZy/nozyzy.github.io"
  issueTerm = "repo"
  label = ""
  lightTheme = "github-light"
  darkTheme = "github-dark"

[params.page.comment.giscus]
  # You can refer to the official documentation of giscus to use the following configuration.
  enable = false
  repo = ""
  repoId = ""
  category = "Announcements"
  categoryId = ""
  # automatically adapt the current theme i18n configuration when empty
  lang = ""
  mapping = "pathname"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  lazyLoading = false
  lightTheme = "light"
  darkTheme = "dark"

# LoveIt NEW | 0.2.7 Third-party library config
[params.page.library]
[params.page.library.css]
# someCSS = "some.css"
# located in "assets/"
# Or
# someCSS = "https://cdn.example.com/some.css"

[params.page.library.js]
# someJavascript = "some.js"
# located in "assets/"
# Or
# someJavascript = "https://cdn.example.com/some.js"
# LoveIt CHANGED | 0.2.10 Page SEO config

[params.page.seo]
# image URL
images = []
# Publisher info

[params.page.seo.publisher]
name = ""
logoUrl = ""

[params.typeit]
  speed = 100
  cursorSpeed = 1000
  cursorChar = "🌭"
  # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
  duration = -1

[params.verification]
  google = ""
  bing = ""
  yandex = ""
  pinterest = ""
  baidu = ""

[params.seo]
  image = ""
  thumbnailUrl = ""

[params.analytics]
  enable = false
